### ISSUE TITLE
Document Search

### ISSUE THREAD

**Issue by grumartin** [grumartin/paperless_monorepo#37]
- Implement the search functionality

Steps:
- Find endpoint in rest-service used for searching documents
- extract query from params and send to elasticsearch
- also make sure to copy the configs for elasticsearch(from ocr service)
- do something with results from elasticsearch??

Maybe this method is called for searching documents since theres no endpoints in searchcontroller(only autocomplete)
![image](https://github.com/grumartin/paperless_monorepo/assets/54779316/d079a05b-8b59-4677-b80f-984f50820bf4)

**Comment by Warteczek** [comment]
Done
